Enhancement/add user search
dogukanarslan/SWE574-Group-3 pull request #55
Opened 2023-04-04 15:33 UTC by mirayiyidogan

User description added
Case sensetive for search has been implemented
Description search added

2023-04-04 15:33 UTC, ilaydakurtboun approved these changes

2023-04-09 08:53 UTC, dogukanarslan requested changes
This PR affects creating a new user. When you try to create a new user in this branch, there is an error message `TypeError: Password must be a string or bytes, got tuple.` . We should fix this before merging.

2023-04-09 14:51 UTC, dogukanarslan approved these changes

2023-04-09 14:54 UTC, afize1 approved these changes

2023-04-09 14:54 UTC, mirayiyidogan commented
Dogukan's comment has been fixed

2023-04-09 14:54 UTC, merged